'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dictionary: Record<string, Record<Language, string>> = {
    // Auth & Common
    'app.title': { en: 'Premium Booking Connect', fr: 'Premium Booking Connect' },
    'login.title': { en: 'Sign In', fr: 'Connexion' },
    'login.subtitle': { en: 'Manage your properties with ease', fr: 'Gérez vos propriétés en toute simplicité' },
    'login.email': { en: 'Email', fr: 'Courriel' },
    'login.password': { en: 'Password', fr: 'Mot de passe' },
    'login.button': { en: 'Sign In', fr: 'Se connecter' },
    'login.no_account': { en: "Don't have an account?", fr: "Pas encore de compte ?" },
    'login.signup': { en: 'Sign Up', fr: "S'inscrire" },
    'login.error': { en: 'Login error', fr: 'Erreur de connexion' },
    'login.password_req': { en: 'Password required', fr: 'Mot de passe requis' },
    'signup.title': { en: 'Sign Up', fr: 'Inscription' },
    'signup.subtitle': { en: 'Start managing your properties', fr: 'Commencez à gérer vos propriétés' },
    'signup.name': { en: 'Full Name', fr: 'Nom complet' },
    'signup.confirm': { en: 'Confirm Password', fr: 'Confirmer le mot de passe' },
    'signup.have_account': { en: 'Already have an account?', fr: 'Déjà un compte ?' },
    'signup.signin': { en: 'Sign In', fr: 'Se connecter' },
    'signup.pass_mismatch': { en: "Passwords don't match", fr: 'Les mots de passe ne correspondent pas' },
    'signup.pass_short': { en: 'Password too short', fr: 'Mot de passe trop court' },
    'signup.error': { en: 'Signup error', fr: "Erreur d'inscription" },
    'signup.check_email': { en: 'Check Your Email', fr: 'Vérifiez votre courriel' },
    'signup.email_sent': { en: 'A confirmation link has been sent to your email address. Please click it to activate your account.', fr: 'Un lien de confirmation a été envoyé à votre adresse courriel. Veuillez cliquer dessus pour activer votre compte.' },

    // Step 1 Labels
    'label.property_name': { en: 'Property Name', fr: 'Nom de la propriété' },
    'label.property_type': { en: 'Property Type', fr: 'Type de propriété' },
    'label.address': { en: 'Address', fr: 'Adresse' },
    'label.google_maps_url': { en: 'Google Maps URL', fr: 'Lien Google Maps' },
    'label.instruction_date': { en: 'Instruction Date', fr: 'Date d\'instruction' },
    'label.num_floors': { en: 'Number of floors', fr: "Nombre d'étages" },
    'label.rooms_on_floor': { en: 'Number of rooms', fr: 'Nombre de chambres' },
    'label.beds_in_bedroom': { en: 'Number of beds', fr: 'Nombre de lits' },
    'label.floor_n': { en: 'Floor {0}', fr: 'Étage {0}' },
    'label.bedroom_n': { en: 'Bedroom {0}', fr: 'Chambre {0}' },
    'label.floor': { en: 'Floor / Suite', fr: 'Étage / Suite' },
    'label.size': { en: 'Property Size', fr: 'Superficie' },
    'label.checkin': { en: 'Check-in Time', fr: "Heure d'arrivée" },
    'label.checkout': { en: 'Check-out Time', fr: 'Heure de départ' },
    'label.documents': { en: 'Official Documents', fr: 'Documents officiels' },
    'label.citq': { en: 'CITQ Certificate', fr: 'Certificat CITQ' },
    'label.reservations': { en: 'Reservations History', fr: 'Historique des réservations' },

    // Dashboard
    'dash.welcome': { en: 'Welcome back', fr: 'Bienvenue' },
    'dash.subtitle': { en: 'Manage your properties and onboardings', fr: 'Gérez vos propriétés et vos mises en service' },
    'dash.new_prop': { en: '+ New Property', fr: '+ Nouvelle propriété' },
    'dash.profile': { en: 'My Profile', fr: 'Mon Profil' },
    'dash.signout': { en: 'Sign Out', fr: 'Déconnexion' },
    'dash.empty': { en: "You haven't added any properties yet.", fr: "Vous n'avez pas encore ajouté de propriétés." },
    'dash.start_onboarding': { en: 'Start Onboarding', fr: 'Commencer' },
    'dash.in_progress': { en: 'In Progress', fr: 'En cours' },
    'dash.completed': { en: 'Completed', fr: 'Terminé' },
    'dash.last_updated': { en: 'Last updated:', fr: 'Dernière mise à jour :' },
    'dash.continue': { en: 'Continue', fr: 'Continuer' },
    'dash.view_details': { en: 'View Details', fr: 'Voir les détails' },

    // Onboarding Steps
    'step.info': { en: 'Property Info', fr: 'Info Propriété' },
    'step.amenity': { en: 'Amenities', fr: 'Équipements' },
    'step.photos': { en: 'Photos', fr: 'Photos' },
    'step.rules': { en: 'Rules & Fees', fr: 'Règles et Frais' },
    'step.guide': { en: 'Guest Guide', fr: 'Guide Invité' },
    'step.payment': { en: 'Payment', fr: 'Paiement' },
    'step.contract': { en: 'Guest Contract', fr: 'Contrat de l’invité' },
    'step.owner_requests': { en: 'Owner Request List', fr: 'Liste des demandes Propriétaire' },
    'step.next': { en: 'Next Step', fr: 'Étape Suivante' },
    'step.back': { en: 'Back', fr: 'Retour' },
    'step.save_exit': { en: 'Save & Exit', fr: 'Sauvegarder & Quitter' },
    'step.comments_label': { en: 'Additional Comments', fr: 'Commentaires additionnels' },
    'step.comments_placeholder': { en: 'Add any specific details or notes here...', fr: 'Ajoutez des détails ou des notes spécifiques ici...' },
    'onboarding.progress_label': { en: 'Onboarding Progress', fr: 'Progression de l\'onboarding' },
    'payment.subtitle': { en: 'Where should we send your payouts?', fr: 'Où devons-nous envoyer vos versements ?' },
    'payment.bank': { en: 'Bank Name', fr: 'Nom de la banque' },
    'payment.holder': { en: 'Account Holder Name', fr: 'Nom du titulaire' },
    'payment.institution': { en: 'Institution Number', fr: "Numéro d'institution" },
    'payment.branch': { en: 'Branch (Transit) Number', fr: 'Numéro de transit (Succursale)' },
    'payment.account': { en: 'Account Number', fr: 'Numéro de compte' },

    // Contract Step
    'contract.title': { en: 'Guest Contract', fr: 'Contrat de l’invité' },
    'contract.subtitle': { en: 'Please review and approve your contract.', fr: 'Veuillez réviser et approuver votre contrat.' },
    'contract.download': { en: 'Download Contract (Word)', fr: 'Télécharger le contrat (Word)' },
    'contract.approve': { en: 'Approve as-is', fr: 'Approuver tel quel' },
    'contract.request_changes': { en: 'Request changes/Add comments', fr: 'Demander des modifications / Ajouter des commentaires' },
    'contract.comments_placeholder': { en: 'Specify any changes, additions, or removals you want...', fr: 'Précisez les changements, ajouts ou retraits que vous souhaitez...' },
    'contract.success': { en: 'Contract feedback saved!', fr: 'Commentaires du contrat enregistrés !' },

    // Photos Step
    'photos.title': { en: 'Property Photos', fr: 'Photos de la Propriété' },
    'photos.subtitle': { en: 'Upload high-quality photos for each area of your property.', fr: 'Téléchargez des photos de haute qualité pour chaque zone de votre propriété.' },
    'photos.zone.living': { en: 'Living Room', fr: 'Salon' },
    'photos.zone.kitchen': { en: 'Kitchen', fr: 'Cuisine' },
    'photos.zone.exterior': { en: 'Exterior/View', fr: 'Extérieur/Vue' },
    'photos.zone.bedroom': { en: 'Bedroom', fr: 'Chambre' },
    'photos.zone.bathroom': { en: 'Bathroom', fr: 'Salle de bain' },
    'photos.zone.plan': { en: 'Floor Plan / Blueprint', fr: 'Plan d\'étage / Plan' },
    'photos.listing_links': { en: 'Previous Listing Links', fr: "Anciens liens de l'annonce" },
    'photos.warning_banner': {
        en: '⚠️ Essential: Some platforms (like Booking.com) block new listings if the property already exists. Tell us where you are published to avoid delays.',
        fr: '⚠️ Information essentielle : Certaines plateformes (comme Booking.com) bloquent la création d\'annonces si la propriété existe déjà. Indiquez-nous vos publications actuelles pour éviter tout retard.'
    },
    'photos.platforms_label': { en: 'On which platforms is your property published?', fr: 'Sur quelles plateformes votre bien est-il publié ?' },
    'photos.platforms_helper': { en: 'The more you tell us, the better we can support you.', fr: 'Plus vous nous en dites, mieux nous pouvons vous accompagner.' },
    'photos.platforms.other_label': { en: 'Specify the platform', fr: 'Précisez la plateforme' },
    'onboarding.step1.floors': { en: 'Floors', fr: 'Étages' },
    'onboarding.step1.bedrooms': { en: 'Bedrooms', fr: 'Chambres' },
    'onboarding.step1.floor': { en: 'Floor', fr: 'Étage' },
    'onboarding.step1.bedroom': { en: 'Bedroom', fr: 'Chambre' },
    'onboarding.step1.beds': { en: 'lits', fr: 'lits' },
    'onboarding.step1.bed': { en: 'lit', fr: 'lit' },
    'ota.airbnb': { en: 'Airbnb', fr: 'Airbnb' },
    'ota.booking': { en: 'Booking.com', fr: 'Booking.com' },
    'ota.vrbo': { en: 'Vrbo / HomeAway', fr: 'Vrbo / HomeAway' },
    'ota.expedia': { en: 'Expedia', fr: 'Expedia' },
    'ota.tripadvisor': { en: 'TripAdvisor', fr: 'TripAdvisor' },
    'ota.abritel': { en: 'Abritel', fr: 'Abritel' },
    'ota.agoda': { en: 'Agoda', fr: 'Agoda' },
    'ota.other': { en: 'Other', fr: 'Autre' },
    'photos.drive_link': { en: 'Google Drive Link', fr: 'Lien Google Drive' },

    // Guest Guide
    'guide.title': { en: 'Guest Guide & Manuals', fr: 'Guide Invité & Manuels' },
    'guide.wifi': { en: 'Wi-Fi', fr: 'Wi-Fi' },
    'guide.checkin': { en: 'Check-in & Security', fr: 'Arrivée & Sécurité' },
    'guide.access_video': { en: 'Unlock/Lock Instruction (Video)', fr: 'Instruction Verrouillage/Déverrouillage (Vidéo)' },
    'guide.kitchen': { en: 'Kitchen', fr: 'Cuisine' },
    'guide.ac': { en: 'Air Conditioning', fr: 'Climatisation' },
    'guide.extras': { en: 'Extras', fr: 'Extras' },
    'guide.luggage': { en: 'Host Luggage List', fr: 'Liste Valise Hôte' },
    'guide.wifi_details': { en: 'Network Name & Password', fr: 'Nom du réseau et mot de passe' },
    'guide.wifi_placeholder': { en: 'Network: MyWifi / Pass: 123456', fr: 'Réseau : MonWifi / Pass : 123456' },
    'guide.wifi_router': { en: 'Router Location (Photo)', fr: 'Emplacement du routeur (Photo)' },
    'guide.wifi_speed': { en: 'Speed Test (Screenshot)', fr: 'Test de vitesse (Capture d\'écran)' },
    'guide.lock_photo': { en: 'Key Box / Lock (Photo)', fr: 'Boîte à clés / Serrure (Photo)' },
    'guide.first_aid': { en: 'First Aid Kit (Photo)', fr: 'Trousse de premiers soins (Photo)' },
    'guide.kitchen_photos': { en: 'Kitchen Utensils (Photos)', fr: 'Ustensiles de cuisine (Photos)' },
    'guide.ac_video': { en: 'AC Instructions (Video)', fr: 'Instructions Climatisation (Vidéo)' },
    'guide.extras_photos': { en: 'Extras: Linens, Baby, Games (Photos)', fr: 'Extras : Draps, bébé, jeux (Photos)' },
    'guide.luggage_description': { en: 'What should guests ABSOLUTELY bring? (e.g., Beach towels, spices...)', fr: 'Que doivent ABSOLUMENT apporter les invités ? (ex: Serviettes de plage, épices...)' },
    'guide.luggage_placeholder': { en: 'List the essentials...', fr: 'Listez les essentiels...' },
    'guide.emergency': { en: 'Emergency Contacts', fr: 'Contacts d\'urgence' },

    // Rules Step
    'rules.smoking': { en: 'Smoking Allowed', fr: 'Fumer autorisé' },
    'rules.pets': { en: 'Pets Allowed', fr: 'Animaux autorisés' },
    'rules.pet_fee': { en: 'Pet Fee ($)', fr: 'Frais pour animaux ($)' },
    'rules.events': { en: 'Events Allowed', fr: 'Événements autorisés' },
    'rules.cleaning': { en: 'I provide cleaning', fr: 'Je m\'occupe du ménage' },
    'rules.max_pets': { en: 'Max Pets Allowed', fr: 'Nombre maximum d\'animaux' },
    'rules.quiet_hours': { en: 'Quiet Hours', fr: 'Heures de calme' },
    'rules.fees_details': { en: 'Fees & Details', fr: 'Frais et détails' },
    'rules.cleaning_fee': { en: 'Cleaning Fee ($)', fr: 'Frais de ménage ($)' },
    'rules.max_guests': { en: 'Max Guests', fr: 'Nombre maximum d\'invités' },
    'rules.access_security': { en: 'Access & Security', fr: 'Accès et Sécurité' },
    'rules.door_code': { en: 'Door Code', fr: 'Code de porte' },
    'rules.lock_type': { en: 'Lock Type', fr: 'Type de serrure' },
    'rules.lock_type.smart': { en: 'Smart Lock', fr: 'Serrure intelligente' },
    'rules.lock_type.lockbox': { en: 'Lockbox', fr: 'Boîte à clés' },
    'rules.lock_brand': { en: 'Lock Brand', fr: 'Marque de la serrure' },
    'rules.lock_brand.other': { en: 'Please specify the brand', fr: 'Précisez la marque' },
    'rules.alarm_code': { en: 'Alarm Code', fr: 'Code d\'alarme' },
    'rules.has_cameras': { en: 'Surveillance Cameras', fr: 'Caméras de surveillance' },
    'rules.num_cameras': { en: 'Number of cameras', fr: 'Nombre de caméras' },
    'rules.camera_placements': { en: 'Camera placements', fr: 'Emplacement des caméras' },
    'rules.ops_contacts': { en: 'Operations Contacts', fr: 'Contacts Opérations' },
    'rules.cleaning_contact': { en: 'Cleaning Team Contact', fr: 'Contact équipe de ménage' },
    'rules.snow_removal': { en: 'Snow Removal Contact', fr: 'Contact déneigement' },
    'rules.additional_notes': { en: 'Additional Notes', fr: 'Notes additionnelles' },
    'guide.video_required': { en: 'Access video is mandatory.', fr: 'La vidéo d\'accès est obligatoire.' },

    // Profile
    'profile.title': { en: 'Owner Profile', fr: 'Profil du propriétaire' },
    'profile.subtitle': { en: 'Complete your information to verify your account.', fr: 'Complétez vos informations pour vérifier votre compte.' },
    'profile.fullname': { en: 'Full Name', fr: 'Nom complet' },
    'profile.phone': { en: 'Phone Number', fr: 'Numéro de téléphone' },
    'profile.email': { en: 'Email', fr: 'Courriel' },
    'profile.section.docs': { en: 'Legal & Financial Documents', fr: 'Documents légaux et financiers' },
    'profile.doc.id': { en: 'Proof of Identity (Passport/License)', fr: "Preuve d'identité (Passeport/Permis)" },
    'profile.doc.void': { en: 'Void Cheque', fr: 'Chèque annulé (Spécimen)' },
    'profile.doc.ins': { en: 'Insurance Attestation', fr: "Attestation d'assurance" },
    'profile.doc.citq': { en: 'CITQ Certificate', fr: 'Certificat CITQ' },
    'profile.tax_confirm': { en: 'I confirm I will handle TPS/TVQ and lodging tax declaration.', fr: "Je confirme que je m'occuperai de la déclaration de TPS/TVQ et de la taxe d'hébergement." },
    'profile.save': { en: 'Save Profile', fr: 'Enregistrer le profil' },
    'profile.saving': { en: 'Saving...', fr: 'Enregistrement...' },
    'profile.uploaded': { en: 'Uploaded', fr: 'Téléchargé' },
    'profile.back': { en: 'Back to Dashboard', fr: 'Retour au tableau de bord' },
    'profile.banking.title': { en: 'Banking Information', fr: 'Informations Bancaires' },
    'profile.banking.canada': { en: 'Canadian Owner', fr: 'Propriétaire Canadien' },
    'profile.banking.intl': { en: 'International Owner', fr: 'Propriétaire International' },
    'profile.banking.canada_instr': { en: 'Please submit a voided cheque only.', fr: 'Veuillez soumettre un chèque annulé uniquement.' },
    'profile.banking.intl_instr': { en: 'Please provide the following information by email:', fr: 'Veuillez nous envoyer les informations suivantes par courriel :' },
    'profile.banking.email_note': { en: 'Banking details should not be uploaded here. Please email these documents directly to us at accounting@premiumbooking.ca.', fr: 'Les coordonnées bancaires ne doivent pas être téléchargées ici. Veuillez nous envoyer ces documents directement par courriel à accounting@premiumbooking.ca.' },
    'profile.banking.intl.holder': { en: 'Full name of account holder', fr: 'Nom complet du titulaire du compte' },
    'profile.banking.intl.bank': { en: 'Bank name', fr: 'Nom de la banque' },
    'profile.banking.intl.address': { en: 'Branch address (if applicable)', fr: 'Adresse de la succursale (si applicable)' },
    'profile.banking.intl.institution': { en: 'Institution number (Canada)', fr: 'Numéro d’institution (Canada)' },
    'profile.banking.intl.transit': { en: 'Transit number (Canada)', fr: 'Numéro de transit (Canada)' },
    'profile.banking.intl.account': { en: 'Account number', fr: 'Numéro de compte' },
    'profile.banking.intl.swift': { en: 'SWIFT / BIC code (if applicable)', fr: 'Code SWIFT / BIC (si applicable)' },
    'profile.banking.intl.iban': { en: 'IBAN (if applicable)', fr: 'IBAN (si applicable)' },
    'profile.banking.intl.currency': { en: 'Account currency', fr: 'Devise du compte' },

    // Amenity Categories
    'amenity.cat.living': { en: 'Living Room', fr: 'Salon' },
    'amenity.cat.kitchen': { en: 'Kitchen', fr: 'Cuisine' },
    'amenity.cat.internet': { en: 'Internet & Office', fr: 'Internet & Bureau' },
    'amenity.cat.heating': { en: 'Heating & Cooling', fr: 'Chauffage & Climatisation' },
    'amenity.cat.laundry': { en: 'Laundry', fr: 'Buanderie' },
    'amenity.cat.baby': { en: 'Baby & Family', fr: 'Bébé & Famille' },
    'amenity.cat.safety': { en: 'Safety & Security', fr: 'Sécurité' },
    'amenity.cat.outdoor': { en: 'Outdoor', fr: 'Extérieur' },
    'amenity.cat.wellness': { en: 'Wellness & Leisure', fr: 'Bien-être & Loisirs' },
    'amenity.cat.parking': { en: 'Parking & Access', fr: 'Parking & Accès' },
    'amenity.cat.pets': { en: 'Pets', fr: 'Animaux' },
    'amenity.cat.features': { en: 'House Features', fr: 'Caractéristiques' },
    'amenity.cat.location': { en: 'Location & Nearby', fr: 'Emplacement & Alentours' },
    'amenity.cat.services': { en: 'Services (Optional)', fr: 'Services (Optionnel)' },
    'amenity.cat.other': { en: 'Other Amenities', fr: 'Autres Équipements' },

    // Amenity Items
    // Living Room
    'amenity.Sofa': { en: 'Sofa', fr: 'Canapé' },
    'amenity.Sofa bed': { en: 'Sofa bed', fr: 'Canapé-lit' },
    'amenity.Armchair': { en: 'Armchair', fr: 'Fauteuil' },
    'amenity.Coffee table': { en: 'Coffee table', fr: 'Table basse' },
    'amenity.TV': { en: 'TV', fr: 'Télévision' },
    'amenity.Smart TV': { en: 'Smart TV', fr: 'Smart TV' },
    'amenity.Cable TV': { en: 'Cable TV', fr: 'Télévision par câble' },
    'amenity.Streaming services': { en: 'Streaming services', fr: 'Services de streaming' },
    'amenity.Sound system': { en: 'Sound system', fr: 'Système audio' },
    'amenity.Board games': { en: 'Board games', fr: 'Jeux de société' },
    'amenity.Books': { en: 'Books', fr: 'Livres' },
    'amenity.Fireplace': { en: 'Fireplace', fr: 'Cheminée' },
    'amenity.Air conditioning': { en: 'Air conditioning', fr: 'Climatisation' },
    'amenity.Heating': { en: 'Heating', fr: 'Chauffage' },
    'amenity.Fan': { en: 'Fan', fr: 'Ventilateur' },
    'amenity.Curtains / blackout curtains': { en: 'Curtains / blackout curtains', fr: 'Rideaux / Rideaux occultants' },
    'amenity.Extra pillows & blankets': { en: 'Extra pillows & blankets', fr: 'Oreillers & couvertures supplémentaires' },

    // Kitchen
    'amenity.Refrigerator': { en: 'Refrigerator', fr: 'Réfrigérateur' },
    'amenity.Freezer': { en: 'Freezer', fr: 'Congélateur' },
    'amenity.Oven': { en: 'Oven', fr: 'Four' },
    'amenity.Microwave': { en: 'Microwave', fr: 'Micro-ondes' },
    'amenity.Stove': { en: 'Stove', fr: 'Cuisinière' },
    'amenity.Dishwasher': { en: 'Dishwasher', fr: 'Lave-vaisselle' },
    'amenity.Coffee machine': { en: 'Coffee machine', fr: 'Machine à café' },
    'amenity.Kettle': { en: 'Kettle', fr: 'Bouilloire' },
    'amenity.Toaster': { en: 'Toaster', fr: 'Grille-pain' },
    'amenity.Blender': { en: 'Blender', fr: 'Mixeur' },
    'amenity.Rice cooker': { en: 'Rice cooker', fr: 'Cuiseur à riz' },
    'amenity.Pots & pans': { en: 'Pots & pans', fr: 'Casseroles & poêles' },
    'amenity.Cooking utensils': { en: 'Cooking utensils', fr: 'Ustensiles de cuisine' },
    'amenity.Plates & bowls': { en: 'Plates & bowls', fr: 'Assiettes & bols' },
    'amenity.Cutlery': { en: 'Cutlery', fr: 'Couverts' },
    'amenity.Wine glasses': { en: 'Wine glasses', fr: 'Verres à vin' },
    'amenity.Cups & mugs': { en: 'Cups & mugs', fr: 'Tasses & mugs' },
    'amenity.Basic cooking essentials': { en: 'Basic cooking essentials', fr: 'Essentiels de cuisine (huile, sel, poivre)' },
    'amenity.Dining table': { en: 'Dining table', fr: 'Table à manger' },

    // Internet & Office
    'amenity.WiFi': { en: 'WiFi', fr: 'WiFi' },
    'amenity.High-speed WiFi': { en: 'High-speed WiFi', fr: 'WiFi haut débit' },
    'amenity.Ethernet connection': { en: 'Ethernet connection', fr: 'Connexion Ethernet' },
    'amenity.Desk': { en: 'Desk', fr: 'Bureau' },
    'amenity.Office chair': { en: 'Office chair', fr: 'Chaise de bureau' },
    'amenity.Printer': { en: 'Printer', fr: 'Imprimante' },

    // Heating & Cooling
    'amenity.Central heating': { en: 'Central heating', fr: 'Chauffage central' },
    'amenity.Portable heater': { en: 'Portable heater', fr: 'Chauffage d\'appoint' },

    // Laundry
    'amenity.Washing machine': { en: 'Washing machine', fr: 'Lave-linge' },
    'amenity.Dryer': { en: 'Dryer', fr: 'Sèche-linge' },
    'amenity.Laundry detergent': { en: 'Laundry detergent', fr: 'Lessive' },
    'amenity.Drying rack': { en: 'Drying rack', fr: 'Étendoir' },

    // Baby & Family
    'amenity.High chair': { en: 'High chair', fr: 'Chaise haute' },
    'amenity.Baby bath': { en: 'Baby bath', fr: 'Baignoire pour bébé' },
    'amenity.Baby monitor': { en: 'Baby monitor', fr: 'Babyphone' },
    'amenity.Changing table': { en: 'Changing table', fr: 'Table à langer' },
    'amenity.Baby safety gates': { en: 'Baby safety gates', fr: 'Barrières de sécurité' },
    'amenity.Outlet covers': { en: 'Outlet covers', fr: 'Cache-prises' },
    'amenity.Children\'s books': { en: 'Children\'s books', fr: 'Livres pour enfants' },
    'amenity.Toys': { en: 'Toys', fr: 'Jouets' },

    // Safety & Security
    'amenity.Smoke detector': { en: 'Smoke detector', fr: 'Détecteur de fumée' },
    'amenity.Carbon monoxide detector': { en: 'Carbon monoxide detector', fr: 'Détecteur de monoxyde de carbone' },
    'amenity.Fire extinguisher': { en: 'Fire extinguisher', fr: 'Extincteur' },
    'amenity.First aid kit': { en: 'First aid kit', fr: 'Trousse de premiers secours' },
    'amenity.Security cameras (outside only)': { en: 'Security cameras (outside only)', fr: 'Caméras de sécurité (extérieur uniquement)' },
    'amenity.Alarm system': { en: 'Alarm system', fr: 'Système d\'alarme' },
    'amenity.Smart lock': { en: 'Smart lock', fr: 'Serrure connectée' },
    'amenity.Keypad lock': { en: 'Keypad lock', fr: 'Serrure à code' },
    'amenity.Lockbox': { en: 'Lockbox', fr: 'Boîte à clés' },
    'amenity.Safe': { en: 'Safe', fr: 'Coffre-fort' },

    // Outdoor
    'amenity.Balcony': { en: 'Balcony', fr: 'Balcon' },
    'amenity.Terrace': { en: 'Terrace', fr: 'Terrasse' },
    'amenity.Patio': { en: 'Patio', fr: 'Patio' },
    'amenity.Garden': { en: 'Garden', fr: 'Jardin' },
    'amenity.Outdoor furniture': { en: 'Outdoor furniture', fr: 'Mobilier extérieur' },
    'amenity.BBQ grill': { en: 'BBQ grill', fr: 'Barbecue' },
    'amenity.Outdoor dining area': { en: 'Outdoor dining area', fr: 'Espace repas extérieur' },
    'amenity.Fire pit': { en: 'Fire pit', fr: 'Brasero' },
    'amenity.Hammock': { en: 'Hammock', fr: 'Hamac' },

    // Wellness & Leisure
    'amenity.Swimming pool (private)': { en: 'Swimming pool (private)', fr: 'Piscine (privée)' },
    'amenity.Swimming pool (shared)': { en: 'Swimming pool (shared)', fr: 'Piscine (partagée)' },
    'amenity.Hot tub / Jacuzzi': { en: 'Hot tub / Jacuzzi', fr: 'Spa / Jacuzzi' },
    'amenity.Sauna': { en: 'Sauna', fr: 'Sauna' },
    'amenity.Gym / fitness equipment': { en: 'Gym / fitness equipment', fr: 'Salle de sport / équipements' },
    'amenity.Yoga mat': { en: 'Yoga mat', fr: 'Tapis de yoga' },
    'amenity.Massage chair': { en: 'Massage chair', fr: 'Fauteuil massant' },

    // Parking & Access
    'amenity.Free parking on premises': { en: 'Free parking on premises', fr: 'Parking gratuit sur place' },
    'amenity.Free street parking': { en: 'Free street parking', fr: 'Parking gratuit dans la rue' },
    'amenity.Paid parking nearby': { en: 'Paid parking nearby', fr: 'Parking payant à proximité' },
    'amenity.EV charger': { en: 'EV charger', fr: 'Borne de recharge VE' },
    'amenity.Elevator': { en: 'Elevator', fr: 'Ascenseur' },
    'amenity.Wheelchair accessible': { en: 'Wheelchair accessible', fr: 'Accessible aux fauteuils roulants' },

    // Pets
    'amenity.Pets allowed': { en: 'Pets allowed', fr: 'Animaux acceptés' },
    'amenity.Pet bowls': { en: 'Pet bowls', fr: 'Gamelles' },
    'amenity.Pet bed': { en: 'Pet bed', fr: 'Lit pour animaux' },
    'amenity.Fenced yard': { en: 'Fenced yard', fr: 'Cour clôturée' },

    // House Features
    'amenity.Smoking allowed': { en: 'Smoking allowed', fr: 'Fumeurs acceptés' },
    'amenity.Long-term stays allowed': { en: 'Long-term stays allowed', fr: 'Séjours longue durée' },
    'amenity.Self check-in': { en: 'Self check-in', fr: 'Arrivée autonome' },
    'amenity.Keyless entry': { en: 'Keyless entry', fr: 'Entrée sans clé' },

    // Location
    'amenity.Beach access': { en: 'Beach access', fr: 'Accès plage' },
    'amenity.Lake access': { en: 'Lake access', fr: 'Accès lac' },
    'amenity.Ski-in / Ski-out': { en: 'Ski-in / Ski-out', fr: 'Accès skis aux pieds' },
    'amenity.Hiking trails nearby': { en: 'Hiking trails nearby', fr: 'Sentiers de randonnée' },
    'amenity.Bike paths': { en: 'Bike paths', fr: 'Pistes cyclables' },
    'amenity.Restaurants nearby': { en: 'Restaurants nearby', fr: 'Restaurants à proximité' },
    'amenity.Public transport nearby': { en: 'Public transport nearby', fr: 'Transports en commun' },
    'amenity.Grocery store nearby': { en: 'Grocery store nearby', fr: 'Épicerie à proximité' },
    'amenity.Tourist attractions nearby': { en: 'Tourist attractions nearby', fr: 'Attractions touristiques' },

    // Services
    'amenity.Cleaning service available': { en: 'Cleaning service available', fr: 'Service de ménage' },
    'amenity.Breakfast available': { en: 'Breakfast available', fr: 'Petit-déjeuner inclus' },
    'amenity.Concierge service': { en: 'Concierge service', fr: 'Conciergerie' },
    'amenity.Airport pickup': { en: 'Airport pickup', fr: 'Navette aéroport' },

    // Bedrooms
    'amenity.Queen bed': { en: 'Queen bed', fr: 'Lit Queen' },
    'amenity.King bed': { en: 'King bed', fr: 'Lit King' },
    'amenity.Double bed': { en: 'Double bed', fr: 'Lit Double' },
    'amenity.Single bed': { en: 'Single bed', fr: 'Lit Simple' },
    'amenity.Bunk bed': { en: 'Bunk bed', fr: 'Lits superposés' },
    'amenity.Crib (baby)': { en: 'Crib (baby)', fr: 'Lit bébé' },
    'amenity.Bedside table': { en: 'Bedside table', fr: 'Table de chevet' },
    'amenity.Reading lamp': { en: 'Reading lamp', fr: 'Lampe de lecture' },
    'amenity.Wardrobe / closet': { en: 'Wardrobe / closet', fr: 'Armoire / Penderie' },
    'amenity.Hangers': { en: 'Hangers', fr: 'Cintres' },
    'amenity.Iron': { en: 'Iron', fr: 'Fer à repasser' },
    'amenity.Ironing board': { en: 'Ironing board', fr: 'Planche à repasser' },
    'amenity.Extra pillows': { en: 'Extra pillows', fr: 'Oreillers supplémentaires' },
    'amenity.Extra blankets': { en: 'Extra blankets', fr: 'Couvertures supplémentaires' },
    'amenity.Desk / workspace': { en: 'Desk / workspace', fr: 'Bureau / Espace de travail' },

    // Bathrooms
    'amenity.Shower': { en: 'Shower', fr: 'Douche' },
    'amenity.Bathtub': { en: 'Bathtub', fr: 'Baignoire' },
    'amenity.Hot water': { en: 'Hot water', fr: 'Eau chaude' },
    'amenity.Shampoo': { en: 'Shampoo', fr: 'Shampoing' },
    'amenity.Conditioner': { en: 'Conditioner', fr: 'Après-shampoing' },
    'amenity.Body soap': { en: 'Body soap', fr: 'Gel douche' },
    'amenity.Towels': { en: 'Towels', fr: 'Serviettes' },
    'amenity.Toilet paper': { en: 'Toilet paper', fr: 'Papier toilette' },
    'amenity.Hair dryer': { en: 'Hair dryer', fr: 'Sèche-cheveux' },
    'amenity.Bidet': { en: 'Bidet', fr: 'Bidet' },
    'amenity.Mirror': { en: 'Mirror', fr: 'Miroir' },
    'amenity.Cleaning products': { en: 'Cleaning products', fr: 'Produits de nettoyage' },

    // Hot Tub
    'amenity.hottub_date': { en: 'Hot Tub Opening Date', fr: "Date d'ouverture du Spa" },
    'amenity.bbq_date': { en: 'BBQ Opening Date', fr: "Date d'ouverture du BBQ" },
    'amenity.pool_date': { en: 'Pool Opening Date', fr: "Date d'ouverture de la piscine" },

    // Property Types
    'property_type.condo': { en: 'Condo', fr: 'Condo' },
    'property_type.apartment': { en: 'Apartment', fr: 'Appartement' },
    'property_type.villa': { en: 'Villa', fr: 'Villa' },
    'property_type.chalet': { en: 'Chalet', fr: 'Chalet' },
    'property_type.other': { en: 'Other', fr: 'Autre' },

    // Admin
    'admin.overview': { en: 'Overview', fr: 'Vue d\'ensemble' },
    'admin.properties': { en: 'Properties', fr: 'Propriétés' },
    'admin.users': { en: 'Users', fr: 'Utilisateurs' },
    'admin.media': { en: 'Media', fr: 'Médias' },
    'admin.logout': { en: 'Logout', fr: 'Déconnexion' },
    'admin.dash.title': { en: 'Dashboard Overview', fr: 'Tableau de Bord' },
    'admin.dash.total_props': { en: 'Total Properties', fr: 'Total Propriétés' },
    'admin.dash.total_clients': { en: 'Total Clients', fr: 'Total Clients' },
    'admin.dash.active': { en: 'Active Onboardings', fr: 'Mises en service actives' },
    'admin.dash.completed': { en: 'Completed', fr: 'Terminé' },
    'admin.dash.recent': { en: 'Recent Activity', fr: 'Activité Récente' },
    'admin.dash.no_activity': { en: 'No recent activity to show.', fr: 'Aucune activité récente.' },

    // Admin Properties
    'admin.props.title': { en: 'All Properties', fr: 'Toutes les Propriétés' },
    'admin.props.search': { en: 'Search properties...', fr: 'Rechercher des propriétés...' },
    'admin.props.table.prop': { en: 'Property', fr: 'Propriété' },
    'admin.props.table.owner': { en: 'Owner ID', fr: 'ID Propriétaire' },
    'admin.props.table.status': { en: 'Status', fr: 'Statut' },
    'admin.props.table.progress': { en: 'Progress', fr: 'Progression' },
    'admin.props.table.updated': { en: 'Last Updated', fr: 'Mise à jour' },
    'admin.props.table.actions': { en: 'Actions', fr: 'Actions' },
    'admin.props.empty': { en: 'No properties found', fr: 'Aucune propriété trouvée' },
    'admin.props.view': { en: 'View', fr: 'Voir' },

    // Admin Users
    'admin.users.title': { en: 'User Management', fr: 'Gestion des Utilisateurs' },
    'admin.users.table.name': { en: 'Full Name', fr: 'Nom Complet' },
    'admin.users.table.email': { en: 'Email', fr: 'Courriel' },
    'admin.users.table.phone': { en: 'Phone', fr: 'Téléphone' },
    'admin.users.table.docs': { en: 'Documents', fr: 'Documents' },
    'admin.users.table.joined': { en: 'Joined', fr: 'Inscription' },
    'admin.users.empty': { en: 'No users found', fr: 'Aucun utilisateur trouvé' },
    'admin.users.download': { en: 'Download', fr: 'Télécharger' },

    // Admin Details Page
    'admin.details.back': { en: 'Back', fr: 'Retour' },
    'admin.details.download_media': { en: 'Download All Media', fr: 'Télécharger tous les médias' },
    'admin.details.download_all_photos': { en: 'Download All Photos', fr: 'Télécharger toutes les photos' },
    'admin.details.download_pdf': { en: 'Download PDF', fr: 'Télécharger PDF' },
    'admin.details.download_citq': { en: 'Download CITQ', fr: 'Télécharger CITQ' },
    'admin.details.citq_not_found': { en: 'No CITQ PDF uploaded', fr: 'Aucun PDF CITQ téléchargé' },
    'admin.details.info.google_maps': { en: 'Google Maps URL', fr: 'Lien Google Maps' },
    'admin.details.info.property_type': { en: 'Property Type', fr: 'Type de propriété' },
    'admin.details.info.floors': { en: 'Floors', fr: 'Étages' },
    'admin.details.info.rooms_dist': { en: 'Rooms per floor', fr: 'Chambres par étage' },
    'admin.details.info.beds_dist': { en: 'Beds per bedroom', fr: 'Lits per chambre' },
    'admin.details.info.total_beds': { en: 'Total beds', fr: 'Lits total' },
    'admin.details.access.platforms': { en: 'Published Platforms', fr: 'Plateformes de publication' },
    'admin.details.rules.smart_lock_brand': { en: 'Smart Lock Brand', fr: 'Marque de la serrure' },
    'admin.details.rules.other_brand': { en: 'Other Brand', fr: 'Autre marque' },
    'admin.details.delete_prop': { en: 'Delete Property', fr: 'Supprimer la propriété' },
    'admin.details.delete_confirm': { en: 'Are you sure you want to delete this property? This action cannot be undone.', fr: 'Êtes-vous sûr de vouloir supprimer cette propriété ? Cette action est irréversible.' },
    'admin.details.delete_success': { en: 'Property deleted successfully', fr: 'Propriété supprimée avec succès' },
    'admin.details.delete_error': { en: 'Error deleting property', fr: 'Erreur lors de la suppression de la propriété' },
    'admin.details.owner_id': { en: 'Owner ID', fr: 'ID Propriétaire' },
    'admin.details.client': { en: 'Client', fr: 'Client' },
    'admin.details.edit': { en: 'Edit', fr: 'Modifier' },
    'admin.details.save': { en: 'Save', fr: 'Sauvegarder' },
    'admin.details.cancel': { en: 'Cancel', fr: 'Annuler' },
    'admin.details.section.info': { en: 'Basic Info', fr: 'Informations de base' },
    'admin.details.section.amenities': { en: 'Amenities', fr: 'Équipements' },
    'admin.details.section.rules': { en: 'Rules & Fees', fr: 'Règles et Frais' },
    'admin.details.section.payment': { en: 'Payment Details', fr: 'Détails de paiement' },
    'admin.details.section.guide': { en: 'Guest Guide & Luggage', fr: 'Guide Invité & Bagages' },
    'admin.details.section.access': { en: 'Uploads & Access', fr: 'Téléchargements & Accès' },
    'admin.details.section.contract': { en: 'Contract Approval', fr: 'Approbation du contrat' },
    'admin.details.info.type': { en: 'Type', fr: 'Type' },
    'admin.details.info.address': { en: 'Address', fr: 'Adresse' },
    'admin.details.info.floor': { en: 'Floor', fr: 'Étage' },
    'admin.details.info.size': { en: 'Size', fr: 'Superficie' },
    'admin.details.info.size_unit': { en: 'Unit', fr: 'Unité' },
    'admin.details.info.rooms': { en: 'Rooms', fr: 'Chambres' },
    'admin.details.info.bed': { en: 'bed', fr: 'lit' },
    'admin.details.info.bath': { en: 'bath', fr: 'sdb' },
    'admin.details.info.checkin': { en: 'Check-in Time', fr: 'Heure d\'arrivée' },
    'admin.details.info.checkout': { en: 'Check-out Time', fr: 'Heure de départ' },
    'admin.details.amenities.comma_list': { en: 'Comma separated list:', fr: 'Liste séparée par des virgules :' },
    'admin.details.rules.smoking': { en: 'Smoking', fr: 'Fumeur' },
    'admin.details.rules.pets': { en: 'Pets', fr: 'Animaux' },
    'admin.details.rules.events': { en: 'Events', fr: 'Événements' },
    'admin.details.rules.max_pets': { en: 'Max Pets', fr: 'Animaux max' },
    'admin.details.rules.cleaning': { en: 'Cleaning Fee', fr: 'Frais de ménage' },
    'admin.details.rules.deposit': { en: 'Security Deposit', fr: 'Dépôt de garantie' },
    'admin.details.rules.pet_fee': { en: 'Pet Fee', fr: 'Frais pour animaux' },
    'admin.details.rules.max_guests': { en: 'Max Guests', fr: 'Nombre max d\'invités' },
    'admin.details.rules.quiet_hours': { en: 'Quiet Hours', fr: 'Heures de silence' },
    'admin.details.rules.access_security': { en: 'Access & Security', fr: 'Accès & Sécurité' },
    'admin.details.rules.door_code': { en: 'Door Code', fr: 'Code porte' },
    'admin.details.rules.lock_type': { en: 'Lock Type', fr: 'Type serrure' },
    'admin.details.rules.alarm_code': { en: 'Alarm Code', fr: 'Code alarme' },
    'admin.details.rules.has_cameras': { en: 'Cameras', fr: 'Caméras' },
    'admin.details.rules.num_cameras': { en: '# Cameras', fr: 'Nb caméras' },
    'admin.details.rules.camera_placements': { en: 'Camera Placements', fr: 'Emplacements caméras' },
    'admin.details.rules.ops_contacts': { en: 'Operations Contacts', fr: 'Contacts Opérations' },
    'admin.details.rules.cleaning_contact': { en: 'Cleaning Team', fr: 'Équipe ménage' },
    'admin.details.rules.snow_removal': { en: 'Snow Removal', fr: 'Déneigement' },
    'admin.details.rules.additional_notes': { en: 'Additional Notes', fr: 'Notes additionnelles' },
    'admin.details.guide.wifi': { en: 'Wi-Fi', fr: 'Wi-Fi' },
    'admin.details.guide.luggage': { en: 'Luggage List', fr: 'Liste de bagages' },
    'admin.details.guide.emergency': { en: 'Emergency Contacts', fr: 'Contacts d\'urgence' },
    'admin.details.guide.router': { en: 'Router Photo', fr: 'Photo du routeur' },
    'admin.details.guide.speedtest': { en: 'Speed Test', fr: 'Test de débit' },
    'admin.details.guide.lock_video': { en: 'Lock Video', fr: 'Vidéo de la serrure' },
    'admin.details.guide.lock_photo': { en: 'Lock/KeyBox', fr: 'Serrure/Boîte à clés' },
    'admin.details.guide.first_aid': { en: 'First Aid Kit', fr: 'Trousse de secours' },
    'admin.details.guide.kitchen': { en: 'Kitchen', fr: 'Cuisine' },
    'admin.details.guide.ac': { en: 'AC Instructions', fr: 'Instructions clim' },
    'admin.details.guide.extras': { en: 'Extras', fr: 'Extras' },
    'admin.details.guide.tour': { en: 'General Tour', fr: 'Visite générale' },
    'admin.details.access.citq': { en: 'CITQ', fr: 'CITQ' },
    'admin.details.access.reservations': { en: 'Reservations (Excel)', fr: 'Réservations (Excel)' },
    'admin.details.access.photos': { en: 'Photos', fr: 'Photos' },
    'admin.details.access.external': { en: 'Past Listing URLs', fr: 'Anciens liens' },
    'admin.details.access.drive': { en: 'Google Drive', fr: 'Google Drive' },
    'admin.details.access.type': { en: 'Access Type', fr: 'Type d\'accès' },
    'admin.details.access.instructions': { en: 'Instructions', fr: 'Instructions' },
    'admin.details.access.tour': { en: 'Tour Video', fr: 'Vidéo de visite' },
    'admin.details.contract.status': { en: 'Status', fr: 'Statut' },
    'admin.details.contract.comments': { en: 'Client Comments', fr: 'Commentaires du client' },
    'admin.details.contract.date': { en: 'Reviewed At', fr: 'Révisé le' },

    // Owner Requests
    'owner_req.spa.title': { en: '1. Spa', fr: '1. Spa' },
    'owner_req.spa.treatment': { en: 'Treatment Type', fr: 'Type de traitement' },
    'owner_req.spa.brome': { en: 'Bromine', fr: 'Brome' },
    'owner_req.spa.chlore': { en: 'Chlorine', fr: 'Chlore' },
    'owner_req.spa.sel': { en: 'Salt', fr: 'Sel' },
    'owner_req.spa.products': { en: 'Products used', fr: 'Produits utilisés' },
    'owner_req.spa.location': { en: 'Location of products', fr: 'Emplacement des produits' },
    'owner_req.spa.contract': { en: 'Spa maintenance contract?', fr: 'Contrat d\'entretien pour le spa ?' },

    'owner_req.bedding.title': { en: '2. Bedding', fr: '2. Literie' },
    'owner_req.bedding.protection': { en: 'Bedding protection', fr: 'Protection literie' },
    'owner_req.bedding.pillows': { en: 'Pillows (Quantity)', fr: 'Oreillers (Quantité)' },
    'owner_req.bedding.blankets': { en: 'Blankets (Quantity)', fr: 'Couvertures (Quantité)' },
    'owner_req.bedding.exchange': { en: 'Exchange linen available?', fr: 'Linge de rechange disponible ?' },

    'owner_req.consumables.title': { en: '3. Consumables', fr: '3. Consommables' },
    'owner_req.consumables.products': { en: 'Products provided', fr: 'Produits fournis' },
    'owner_req.consumables.refill': { en: 'Who manages refills?', fr: 'Qui gère le réapprovisionnement ?' },
    'owner_req.consumables.budget': { en: 'Approximate budget', fr: 'Budget approximatif' },
    'owner_req.consumables.currency': { en: 'Currency', fr: 'Devise' },

    'owner_req.bbq.title': { en: '4. Propane / BBQ', fr: '4. Propane / BBQ' },
    'owner_req.bbq.propane': { en: 'Propane available?', fr: 'Propane disponible ?' },
    'owner_req.bbq.gauge': { en: 'Presence of a gauge', fr: 'Présence d\'un gauge (indicateur de niveau)' },
    'owner_req.bbq.procedure': { en: 'Procedure if bottle is empty', fr: 'Procédure si bouteille vide' },

    'owner_req.emergency.title': { en: '5. Emergency Kit', fr: '5. Kit d\'urgence' },
    'owner_req.emergency.presence': { en: 'Presence of an emergency kit', fr: 'Présence d\'un kit d\'urgence' },
    'owner_req.emergency.content': { en: 'Kit content', fr: 'Contenu du kit' },
    'owner_req.emergency.first_aid': { en: 'First aid kit', fr: 'Trousse de premiers secours' },
    'owner_req.emergency.flashlight': { en: 'Flashlight', fr: 'Lampe de poche' },
    'owner_req.emergency.batteries': { en: 'Batteries', fr: 'Piles' },
    'owner_req.emergency.location': { en: 'Kit location', fr: 'Emplacement du kit' },

    'owner_req.expense.title': { en: '6. Expense Authorization', fr: '6. Autorisation de dépenses' },
    'owner_req.expense.max_amount': { en: 'Maximum amount without validation', fr: 'Montant maximum sans validation' },
    'owner_req.expense.types': { en: 'Types of allowed expenses', fr: 'Types de dépenses autorisées' },
    'owner_req.expense.comm_mode': { en: 'Preferred communication mode', fr: 'Mode de communication préféré' },
    'owner_req.common.save': { en: 'Save / Update', fr: 'Sauvegarder / Mettre à jour' },
    'owner_req.common.yes': { en: 'Yes', fr: 'Oui' },
    'owner_req.common.no': { en: 'No', fr: 'Non' },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const stored = localStorage.getItem('app_lang') as Language;
        if (stored) setLanguage(stored);
    }, []);

    const changeLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('app_lang', lang);
    };

    const t = (key: string) => {
        return dictionary[key]?.[language] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
    return context;
}
